sudo: required

services:
  - docker

language: node_js

os:
  - linux

before_script:
  - npm i @npm-wharf/shipwright@latest -g

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - shipwright build image --repo=npmwharf --name=k8s-route53bot --cache-from-latest --tags=lm,v,miv

node_js:
  - "8"
